\App\Models\Setting::__set_state(array( 'connection' => 'mysql', 'table' => 'settings', 'primaryKey' => 'id', 'keyType' => 'int', 'incrementing' => true, 'with' => array ( ), 'withCount' => array ( ), 'preventsLazyLoading' => false, 'perPage' => 15, 'exists' => true, 'wasRecentlyCreated' => false, 'escapeWhenCastingToString' => false, 'attributes' => array ( 'id' => 1, 'business_name' => 'Doctro', 'email' => 'doctro@example.com', 'phone' => '774455662211', 'company_white_logo' => '63e38d29b18f4.png', 'company_logo' => '63e38d29b1d7f.png', 'company_favicon' => '63f6efb85dbc2.png', 'currency_symbol' => '$', 'currency_code' => 'USD', 'currency_id' => 2, 'color' => '#1f8ced', 'website_color' => '#2782ff', 'cod' => 1, 'stripe' => 0, 'paypal' => 0, 'razor' => 0, 'flutterwave' => 0, 'paystack' => 0, 'stripe_public_key' => ' ', 'stripe_secret_key' => ' ', 'paypal_secret_key' => ' ', 'paypal_client_id' => ' ', 'razor_key' => ' ', 'flutterwave_key' => ' ', 'flutterwave_encryption_key' => ' ', 'isLiveKey' => 0, 'paystack_public_key' => ' ', 'timezone' => 'Asia/Kolkata', 'default_commission' => 10, 'pharmacy_commission' => 10, 'pharamacy_commission' => 10, 'default_base_on' => 'commission', 'map_key' => '', 'verification' => 0, 'using_mail' => 0, 'using_msg' => 0, 'twilio_auth_token' => ' ', 'twilio_acc_id' => ' ', 'twilio_phone_no' => ' ', 'mail_mailer' => ' ', 'mail_host' => ' ', 'mail_port' => ' ', 'mail_username' => ' ', 'mail_password' => ' ', 'mail_encryption' => ' ', 'mail_from_address' => ' ', 'mail_from_name' => ' ', 'cancel_reason' => '["appointment time doctor not available.","Now I am perfectly alright.","Hospital not find and I missed appointment time.","Personal Reasons"]', 'radius' => 100, 'clinic_content' => '

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
', 'doctor_content' => '

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum.


web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes
', 'footer_content' => '

﻿In layman\'s terms, ﻿Lorem Ipsu﻿m is a dummy or placeho﻿ld﻿er text. It\'s often used in laying out print, infographics, or web design
', 'doctor_mail' => '0', 'patient_mail' => '0', 'patient_notification' => '0', 'doctor_notification' => '0', 'patient_app_id' => ' ', 'patient_auth_key' => ' ', 'patient_api_key' => ' ', 'doctor_app_id' => ' ', 'doctor_auth_key' => ' ', 'doctor_api_key' => ' ', 'license_code' => '', 'client_name' => '', 'license_verify' => 0, 'language' => 'English', 'auto_cancel' => '60', 'playstore' => 'https://doctro.saasmonks.in', 'appstore' => 'https://doctro.saasmonks.in', 'privacy_policy' => NULL, 'about_us' => '


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vestibulum, velit quis pretium egestas, lorem dui finibus mauris, a lacinia orci quam nec metus. Nam ut dui enim. Vestibulum lorem turpis, dictum sit amet sollicitudin ut, sagittis non massa. Praesent mollis tortor non dapibus porttitor. Nam pretium metus nunc, sit amet placerat tellus semper at. Duis pretium elit eu eros cursus, sit amet aliquam neque rutrum. Nulla facilisi. Phasellus condimentum pharetra enim nec tempor. Mauris non cursus velit. Vestibulum venenatis elementum tellus non condimentum. Curabitur at ultricies arcu. Integer pharetra ante ac magna luctus, sit amet ullamcorper nunc bibendum. Aenean hendrerit consectetur massa ac fringilla. Mauris tristique nulla eu eleifend dignissim. Cras consequat faucibus arcu, non semper velit gravida tincidunt.

Duis quam augue, semper non felis tincidunt, cursus suscipit elit. Curabitur quis iaculis enim. Nulla facilisi. Nam nec orci a mauris condimentum dictum. Maecenas eros diam, aliquet eget lorem eget, aliquam fermentum tortor. Vivamus vehicula mauris est, id rhoncus arcu pellentesque vel. Vestibulum id hendrerit nunc. Sed purus leo, faucibus vitae tincidunt in, auctor sed mi.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque risus arcu, luctus in lectus et, finibus eleifend tellus. Praesent mauris ex, consectetur quis egestas vitae, auctor sed libero. Nulla commodo, orci malesuada accumsan vehicula, ex leo tempus magna, id cursus sem dui eget nunc. In fringilla magna quis purus pulvinar varius. Proin non libero lectus. Sed non aliquet purus. Cras cursus ullamcorper eros, et rhoncus odio pharetra ac. Aliquam posuere tellus a accumsan imperdiet. Vivamus tristique erat maximus ornare maximus. In hac habitasse platea dictumst. Praesent at tempor lacus. Donec gravida neque non blandit auctor. Vivamus nec tincidunt lectus.

Nam quis risus mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus vehicula nisi non urna mattis, at vulputate nisi cursus. Aenean in quam eu odio pellentesque imperdiet. Morbi sed nulla non urna tempor gravida. Aenean at vehicula enim. Donec volutpat vulputate mattis.

Morbi placerat, dolor ac mollis tincidunt, erat ligula mattis ligula, et ultricies mi nisi et elit. Curabitur ornare a nunc et fermentum. Suspendisse potenti. Proin vel pulvinar dolor. Nulla justo ante, efficitur a elementum sit amet, egestas fringilla ante. Nulla vitae placerat neque, eget sollicitudin augue. Aliquam quis ante id lacus euismod facilisis non a sapien. Sed vitae ante non justo dignissim venenatis. Quisque maximus eleifend est, vitae malesuada turpis ultrices at. Aliquam pulvinar urna sed dui mollis, a bibendum lectus consequat. Ut condimentum dolor et efficitur lobortis. Morbi tempor tincidunt felis, pretium congue mi. Maecenas finibus, massa vel blandit volutpat, velit nisl finibus elit, id hendrerit tortor tortor nec purus. Sed venenatis, turpis a luctus gravida, odio magna sodales neque, nec consequat odio odio sed libero. Aliquam erat volutpat. Fusce imperdiet, quam vel dignissim dictum, sapien velit convallis risus, vitae porttitor velit ex quis arcu.
', 'agora_app_id' => NULL, 'agora_app_certificate' => NULL, 'banner_image' => '63e38dd64a28a.png', 'banner_url' => 'https://doctro.saasmonks.in', 'pathologist_commission' => 10, 'facebook_url' => 'https://doctro.saasmonks.in', 'linkdin_url' => 'https://doctro.saasmonks.in', 'instagram_url' => 'https://doctro.saasmonks.in', 'twitter_url' => 'https://doctro.saasmonks.in', 'home_content' => 'Browse by Specialities', 'home_content_desc' => '

Lorem ipsum dolor sit amet, elit. Euismod habitasse pulvinar faucibus eget.Lorem ipsum dolor sit amet, elit. Euismod habitasse pulvinar faucibus eget.
', 'lat' => '40.7127281', 'lang' => '-74.0060152', 'created_at' => '2021-04-16 07:59:47', 'updated_at' => '2023-02-08 17:41:17', ), 'original' => array ( 'id' => 1, 'business_name' => 'Doctro', 'email' => 'doctro@example.com', 'phone' => '774455662211', 'company_white_logo' => '63e38d29b18f4.png', 'company_logo' => '63e38d29b1d7f.png', 'company_favicon' => '63f6efb85dbc2.png', 'currency_symbol' => '$', 'currency_code' => 'USD', 'currency_id' => 2, 'color' => '#1f8ced', 'website_color' => '#2782ff', 'cod' => 1, 'stripe' => 0, 'paypal' => 0, 'razor' => 0, 'flutterwave' => 0, 'paystack' => 0, 'stripe_public_key' => ' ', 'stripe_secret_key' => ' ', 'paypal_secret_key' => ' ', 'paypal_client_id' => ' ', 'razor_key' => ' ', 'flutterwave_key' => ' ', 'flutterwave_encryption_key' => ' ', 'isLiveKey' => 0, 'paystack_public_key' => ' ', 'timezone' => 'Asia/Kolkata', 'default_commission' => 10, 'pharmacy_commission' => 10, 'pharamacy_commission' => 10, 'default_base_on' => 'commission', 'map_key' => '', 'verification' => 0, 'using_mail' => 0, 'using_msg' => 0, 'twilio_auth_token' => ' ', 'twilio_acc_id' => ' ', 'twilio_phone_no' => ' ', 'mail_mailer' => ' ', 'mail_host' => ' ', 'mail_port' => ' ', 'mail_username' => ' ', 'mail_password' => ' ', 'mail_encryption' => ' ', 'mail_from_address' => ' ', 'mail_from_name' => ' ', 'cancel_reason' => '["appointment time doctor not available.","Now I am perfectly alright.","Hospital not find and I missed appointment time.","Personal Reasons"]', 'radius' => 100, 'clinic_content' => '

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
', 'doctor_content' => '

It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum.


web page editors now use Lorem Ipsum as their default model text, and a search for \'lorem ipsum\' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes
', 'footer_content' => '

﻿In layman\'s terms, ﻿Lorem Ipsu﻿m is a dummy or placeho﻿ld﻿er text. It\'s often used in laying out print, infographics, or web design
', 'doctor_mail' => '0', 'patient_mail' => '0', 'patient_notification' => '0', 'doctor_notification' => '0', 'patient_app_id' => ' ', 'patient_auth_key' => ' ', 'patient_api_key' => ' ', 'doctor_app_id' => ' ', 'doctor_auth_key' => ' ', 'doctor_api_key' => ' ', 'license_code' => '', 'client_name' => '', 'license_verify' => 0, 'language' => 'English', 'auto_cancel' => '60', 'playstore' => 'https://doctro.saasmonks.in', 'appstore' => 'https://doctro.saasmonks.in', 'privacy_policy' => NULL, 'about_us' => '


Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc vestibulum, velit quis pretium egestas, lorem dui finibus mauris, a lacinia orci quam nec metus. Nam ut dui enim. Vestibulum lorem turpis, dictum sit amet sollicitudin ut, sagittis non massa. Praesent mollis tortor non dapibus porttitor. Nam pretium metus nunc, sit amet placerat tellus semper at. Duis pretium elit eu eros cursus, sit amet aliquam neque rutrum. Nulla facilisi. Phasellus condimentum pharetra enim nec tempor. Mauris non cursus velit. Vestibulum venenatis elementum tellus non condimentum. Curabitur at ultricies arcu. Integer pharetra ante ac magna luctus, sit amet ullamcorper nunc bibendum. Aenean hendrerit consectetur massa ac fringilla. Mauris tristique nulla eu eleifend dignissim. Cras consequat faucibus arcu, non semper velit gravida tincidunt.

Duis quam augue, semper non felis tincidunt, cursus suscipit elit. Curabitur quis iaculis enim. Nulla facilisi. Nam nec orci a mauris condimentum dictum. Maecenas eros diam, aliquet eget lorem eget, aliquam fermentum tortor. Vivamus vehicula mauris est, id rhoncus arcu pellentesque vel. Vestibulum id hendrerit nunc. Sed purus leo, faucibus vitae tincidunt in, auctor sed mi.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Pellentesque risus arcu, luctus in lectus et, finibus eleifend tellus. Praesent mauris ex, consectetur quis egestas vitae, auctor sed libero. Nulla commodo, orci malesuada accumsan vehicula, ex leo tempus magna, id cursus sem dui eget nunc. In fringilla magna quis purus pulvinar varius. Proin non libero lectus. Sed non aliquet purus. Cras cursus ullamcorper eros, et rhoncus odio pharetra ac. Aliquam posuere tellus a accumsan imperdiet. Vivamus tristique erat maximus ornare maximus. In hac habitasse platea dictumst. Praesent at tempor lacus. Donec gravida neque non blandit auctor. Vivamus nec tincidunt lectus.

Nam quis risus mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus vehicula nisi non urna mattis, at vulputate nisi cursus. Aenean in quam eu odio pellentesque imperdiet. Morbi sed nulla non urna tempor gravida. Aenean at vehicula enim. Donec volutpat vulputate mattis.

Morbi placerat, dolor ac mollis tincidunt, erat ligula mattis ligula, et ultricies mi nisi et elit. Curabitur ornare a nunc et fermentum. Suspendisse potenti. Proin vel pulvinar dolor. Nulla justo ante, efficitur a elementum sit amet, egestas fringilla ante. Nulla vitae placerat neque, eget sollicitudin augue. Aliquam quis ante id lacus euismod facilisis non a sapien. Sed vitae ante non justo dignissim venenatis. Quisque maximus eleifend est, vitae malesuada turpis ultrices at. Aliquam pulvinar urna sed dui mollis, a bibendum lectus consequat. Ut condimentum dolor et efficitur lobortis. Morbi tempor tincidunt felis, pretium congue mi. Maecenas finibus, massa vel blandit volutpat, velit nisl finibus elit, id hendrerit tortor tortor nec purus. Sed venenatis, turpis a luctus gravida, odio magna sodales neque, nec consequat odio odio sed libero. Aliquam erat volutpat. Fusce imperdiet, quam vel dignissim dictum, sapien velit convallis risus, vitae porttitor velit ex quis arcu.
', 'agora_app_id' => NULL, 'agora_app_certificate' => NULL, 'banner_image' => '63e38dd64a28a.png', 'banner_url' => 'https://doctro.saasmonks.in', 'pathologist_commission' => 10, 'facebook_url' => 'https://doctro.saasmonks.in', 'linkdin_url' => 'https://doctro.saasmonks.in', 'instagram_url' => 'https://doctro.saasmonks.in', 'twitter_url' => 'https://doctro.saasmonks.in', 'home_content' => 'Browse by Specialities', 'home_content_desc' => '

Lorem ipsum dolor sit amet, elit. Euismod habitasse pulvinar faucibus eget.Lorem ipsum dolor sit amet, elit. Euismod habitasse pulvinar faucibus eget.
', 'lat' => '40.7127281', 'lang' => '-74.0060152', 'created_at' => '2021-04-16 07:59:47', 'updated_at' => '2023-02-08 17:41:17', ), 'changes' => array ( ), 'casts' => array ( ), 'classCastCache' => array ( ), 'attributeCastCache' => array ( ), 'dates' => array ( ), 'dateFormat' => NULL, 'appends' => array ( 0 => 'companyWhite', 1 => 'logo', 2 => 'favicon', ), 'dispatchesEvents' => array ( ), 'observables' => array ( ), 'relations' => array ( ), 'touches' => array ( ), 'timestamps' => true, 'hidden' => array ( ), 'visible' => array ( ), 'fillable' => array ( 0 => 'company_white_logo', 1 => 'phone', 2 => 'email', 3 => 'company_logo', 4 => 'company_favicon', 5 => 'currency_symbol', 6 => 'currency_code', 7 => 'currency_id', 8 => 'color', 9 => 'timezone', 10 => 'business_name', 11 => 'cod', 12 => 'paypal', 13 => 'stripe', 14 => 'razor', 15 => 'flutterwave', 16 => 'paystack', 17 => 'stripe_public_key', 18 => 'stripe_secret_key', 19 => 'razor_key', 20 => 'flutterwave_encryption_key', 21 => 'isLiveKey', 22 => 'default_commission', 23 => 'default_base_on', 24 => 'map_key', 25 => 'verification', 26 => 'using_mail', 27 => 'using_msg', 28 => 'twilio_auth_token', 29 => 'twilio_acc_id', 30 => 'twilio_phone_no', 31 => 'mail_mailer', 32 => 'mail_host', 33 => 'mail_port', 34 => 'mail_username', 35 => 'mail_password', 36 => 'mail_encryption', 37 => 'mail_from_address', 38 => 'mail_from_name', 39 => 'flutterwave_key', 40 => 'paystack_public_key', 41 => 'cancel_reason', 42 => 'website_color', 43 => 'pharmacy_commission', 44 => 'radius', 45 => 'auto_cancel', 46 => 'patient_notification', 47 => 'doctor_notification', 48 => 'patient_app_id', 49 => 'patient_auth_key', 50 => 'patient_api_key', 51 => 'doctor_app_id', 52 => 'doctor_auth_key', 53 => 'doctor_api_key', 54 => 'patient_mail', 55 => 'doctor_mail', 56 => 'license_code', 57 => 'client_name', 58 => 'license_verify', 59 => 'language', 60 => 'playstore', 61 => 'appstore', 62 => 'privacy_policy', 63 => 'about_us', 64 => 'agora_app_id', 65 => 'agora_app_certificate', 66 => 'banner_image', 67 => 'landing_popup_image', 68 => 'popup_timer_seconds', 69 => 'popup_target_url', 70 => 'landing_popup_switch', 71 => 'banner_url', 72 => 'pathologist_commission', 73 => 'paypal_client_id', 74 => 'paypal_secret_key', 75 => 'facebook_url', 76 => 'linkdin_url', 77 => 'instagram_url', 78 => 'twitter_url', 79 => 'home_content', 80 => 'home_content_desc', 81 => 'lat', 82 => 'lang', ), 'guarded' => array ( 0 => '*', ), ))
